[package]
name = "dark_pig_git"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
dotenv = "0.15.0"
git2 = "0.20.3"
gpui = { version = "*" }
# lyon = {version = "1", features = ["extra"]}
